model_params:
  name: 'WAE_MMD_REP'
  in_channels: 3
  latent_dim: 128
  reg_weight: 5000
  kernel_type: 'rbf'
  recon_factor: 10

data_params:
  data_path: "/home/nih/nih-elda-var/Studies_under_Helsinki_approval/Emek_US_to_CT_Dr_Elik_Aharony/datasets/VAE/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  gpus: [0]
  max_epochs: 10

logging_params:
  save_dir: "/home/nih/nih-elda-var/Studies_under_Helsinki_approval/Emek_US_to_CT_Dr_Elik_Aharony/checkpoints/VAE/"
  version: 5
  checkpoint: "epoch=7-step=20351.ckpt"
  results_dir: "/home/nih/nih-elda-var/Studies_under_Helsinki_approval/Emek_US_to_CT_Dr_Elik_Aharony/results/vae/wae_mmd_rep/"
  name: "WassersteinVAE_RBF"





